[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_KLEROS_LIQUID_KOVAN_ADDRESS='0x15e0016cf021c3f20da31da3350281cd0039b763'
  REACT_APP_PINAKION_KOVAN_ADDRESS='0x1ee318dbc19267dbce08f54a66ab198f73ede356'
  REACT_APP_POLICY_REGISTRY_KOVAN_ADDRESS='0xfc53d1d6ddc2c6cdd403cb7dbf0f26140d82e12d'
  REACT_APP_WEB3_FALLBACK_URL='wss://mainnet.infura.io/ws'
  REACT_APP_PATCH_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings'

[context.production.environment]
  REACT_APP_PATCH_USER_SETTINGS_URL='https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
