[build.environment]
  YARN_FLAGS='--pure-lockfile'
  NODE_VERSION='10.23.2'
  REACT_APP_CONTEXT='staging'
  REACT_APP_KLEROS_KOVAN_ADDRESS='0x0ce74f00cb060555a61602c2e6b31eca5e4c6851'
  REACT_APP_KLEROS_LIQUID_KOVAN_ADDRESS='0x60b2abfdfad9c0873242f59f2a8c32a3cc682f80'
  REACT_APP_KLEROS_LIQUID_EXTRA_VIEWS_KOVAN_ADDRESS='0x2249b99b6f7df65e576bd6e174a301045b61c2d9'
  REACT_APP_PINAKION_KOVAN_ADDRESS='0x1ee318dbc19267dbce08f54a66ab198f73ede356'
  REACT_APP_POLICY_REGISTRY_KOVAN_ADDRESS='0xfc53d1d6ddc2c6cdd403cb7dbf0f26140d82e12d'
  REACT_APP_UNISWAP_EXCHANGE_KOVAN_ADDRESS='0xc06d2318da0609f80c3c50463a4b646a20acdae7'
  REACT_APP_KLEROS_ADDRESS='0x211f01e59b425253c0a0e9a7bf612605b42ce82c'
  REACT_APP_KLEROS_LIQUID_ADDRESS='0x988b3a538b618c7a603e1c11ab82cd16dbe28069'
  REACT_APP_KLEROS_LIQUID_EXTRA_VIEWS_ADDRESS='0xda47f3252bb03c5c7950d7bb2fd32637fc5ad943'
  REACT_APP_PINAKION_ADDRESS='0x93ed3fbe21207ec2e8f2d3c3de6e058cb73bc04d'
  REACT_APP_POLICY_REGISTRY_ADDRESS='0xCf1f07713d5193FaE5c1653C9f61953D048BECe4'
  REACT_APP_UNISWAP_EXCHANGE_ADDRESS='0xF506828B166de88cA2EDb2A98D960aBba0D2402A'
  REACT_APP_DRAW_EVENT_LISTENER_BLOCK_NUMBER='7303699'
  REACT_APP_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings'
  REACT_APP_JUSTIFICATIONS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/justifications'
  REACT_APP_APPLICATION_SERVER_KEY='BNqPp3phfZUqu4G1SCkqNuZ_FDL4YuSeAEV97U_G3UbrOuOsTeaI9jHE3QNRJ-O8EH3F2OUdnJJ4ZOhp80FthKU'
  REACT_APP_WEB3_FALLBACK_URL='wss://mainnet.infura.io/ws/v3/54fb3d87cd07464591ad2be29a1db32f'
  REACT_APP_KLEROS_LIQUID_ROPSTEN_ADDRESS='0xab942e7d2bff0bc5614c968ccc91198fd223c57e'
  REACT_APP_KLEROS_LIQUID_EXTRA_VIEWS_ROPSTEN_ADDRESS='0x50ff088a61b39045f35d8308d91984e8a7e94810'
  REACT_APP_PINAKION_ROPSTEN_ADDRESS='0xD042ef7eDFa1d39146a25f9cb87b274c422cCEb2'
  REACT_APP_POLICY_REGISTRY_ROPSTEN_ADDRESS='0xe4ee06e5c9921d7e4d4ab62199c8c4b5267a7547'

[context.production.environment]
  REACT_APP_CONTEXT='production'
  REACT_APP_USER_SETTINGS_URL='https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings'
  REACT_APP_JUSTIFICATIONS_URL='https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/justifications'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://kleros-court.netlify.com/*"
  to = "https://court.kleros.io/:splat"
  status = 301
  force = true
