[build.environment]
  YARN_FLAGS='--pure-lockfile'
  NODE_VERSION='16.20.2'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://kleros-court.netlify.com/*"
  to = "https://court.kleros.io/:splat"
  status = 301
  force = true
