[build.environment]
  YARN_FLAGS='--pure-lockfile'
  NODE_VERSION='16.20.2'
  REACT_APP_CONTEXT='staging'

  REACT_APP_KLEROS_ADDRESS='0x211f01e59b425253c0a0e9a7bf612605b42ce82c'
  REACT_APP_KLEROS_LIQUID_ADDRESS='0x988b3a538b618c7a603e1c11ab82cd16dbe28069'
  REACT_APP_KLEROS_LIQUID_EXTRA_VIEWS_ADDRESS='0x2B562ea613ad2f58746935C842d09EB147E1E940'
  REACT_APP_PINAKION_ADDRESS='0x93ed3fbe21207ec2e8f2d3c3de6e058cb73bc04d'
  REACT_APP_POLICY_REGISTRY_ADDRESS='0xCf1f07713d5193FaE5c1653C9f61953D048BECe4'
  REACT_APP_UNISWAP_EXCHANGE_ADDRESS='0xF506828B166de88cA2EDb2A98D960aBba0D2402A'
  REACT_APP_TOKEN_BRIDGE_ADDRESS='0x88ad09518695c6c3712AC10a214bE5109a655671'
  REACT_APP_DRAW_EVENT_LISTENER_BLOCK_NUMBER='7303699'
  REACT_APP_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings'
  REACT_APP_JUSTIFICATIONS_URL='https://kleros-api.netlify.app/.netlify/functions'
  REACT_APP_METAEVIDENCE_URL='https://kleros-api.netlify.app/.netlify/functions/get-dispute-metaevidence'
  REACT_APP_APPLICATION_SERVER_KEY='BNqPp3phfZUqu4G1SCkqNuZ_FDL4YuSeAEV97U_G3UbrOuOsTeaI9jHE3QNRJ-O8EH3F2OUdnJJ4ZOhp80FthKU'

  REACT_APP_KLEROS_LIQUID_CHIADO_ADDRESS='0xD8798DfaE8194D6B4CD6e2Da6187ae4209d06f27'
  REACT_APP_KLEROS_LIQUID_EXTRA_VIEWS_CHIADO_ADDRESS='0xfDD698D6c9393d08c5DaD8488AF6d08c151e4860'
  REACT_APP_PINAKION_CHIADO_ADDRESS='0xA353A70c8B3C7d38A869436d4CDeBe8e5611681a'
  REACT_APP_POLICY_REGISTRY_CHIADO_ADDRESS='0x53FC70FE1EC3a60f8939A62aBCc61bf1A57938D7'
  REACT_APP_TOKEN_BRIDGE_CHIADO_ADDRESS='0x09D549a48AC52F3f9945E7de6402c609c92aa2E1'
  REACT_APP_KLEROS_LIQUID_CHIADO_BLOCK_NUMBER='1165867'

  REACT_APP_KLEROS_LIQUID_SEPOLIA_ADDRESS='0x90992fb4E15ce0C59aEFfb376460Fda4Ee19C879'
  REACT_APP_KLEROS_LIQUID_EXTRA_VIEWS_SEPOLIA_ADDRESS='0x5562Ac605764DC4039fb6aB56a74f7321396Cdf2'
  REACT_APP_PINAKION_SEPOLIA_ADDRESS='0xA1eE4D32bdBcA69cdb445D66fAA3804aFFa24bFE'
  REACT_APP_POLICY_REGISTRY_SEPOLIA_ADDRESS='0x88Fb25D399310c07d35cB9091b8346d8b1893aa5'
  REACT_APP_KLEROS_LIQUID_SEPOLIA_BLOCK_NUMBER='3635742'

  REACT_APP_KLEROS_XDAI_ADDRESS='0x0000000000000000000000000000000000000000'
  REACT_APP_KLEROS_LIQUID_XDAI_ADDRESS='0x9C1dA9A04925bDfDedf0f6421bC7EEa8305F9002'
  REACT_APP_KLEROS_LIQUID_EXTRA_VIEWS_XDAI_ADDRESS='0x1c0D5A1fF532715a58d0456ef10532e3eb6ec5de'
  REACT_APP_PINAKION_XDAI_ADDRESS='0xcb3231aBA3b451343e0Fddfc45883c842f223846'
  REACT_APP_RAW_PINAKION_XDAI_ADDRESS='0x37b60f4e9a31a64ccc0024dce7d0fd07eaa0f7b3'
  REACT_APP_POLICY_REGISTRY_XDAI_ADDRESS='0x9d494768936b6bDaabc46733b8D53A937A6c6D7e'
  REACT_APP_UNISWAP_V2_ROUTER_02_XDAI_ADDRESS='0x0000000000000000000000000000000000000000'
  REACT_APP_UNISWAP_V2_FACTORY_XDAI_ADDRESS='0x0000000000000000000000000000000000000000'
  REACT_APP_TOKEN_BRIDGE_XDAI_ADDRESS='0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d'
  REACT_APP_KLEROS_LIQUID_XDAI_BLOCK_NUMBER='16895601'

[context.production.environment]
  REACT_APP_CONTEXT='production'
  REACT_APP_USER_SETTINGS_URL='https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings'
  REACT_APP_JUSTIFICATIONS_URL='https://kleros-api.netlify.app/.netlify/functions'
  REACT_APP_METAEVIDENCE_URL='https://kleros-api.netlify.app/.netlify/functions/get-dispute-metaevidence'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://kleros-court.netlify.com/*"
  to = "https://court.kleros.io/:splat"
  status = 301
  force = true
